#PBS -e ./sysout/obs_yr1_file1.$PBS_JOBID.err
#PBS -o ./sysout/obs_yr1_file1.$PBS_JOBID.out
#PBS -e ./sysout/obs_yr2_file1.$PBS_JOBID.err
#PBS -o ./sysout/obs_yr2_file1.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file1.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file1.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file2.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file2.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file3.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file3.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file4.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file4.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file5.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file5.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file6.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file6.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file7.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file7.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file8.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file8.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file9.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file9.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file10.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file10.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file1.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file1.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file2.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file2.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file3.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file3.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file4.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file4.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file5.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file5.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file6.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file6.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file7.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file7.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file8.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file8.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file9.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file9.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file10.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file10.$PBS_JOBID.out
#PBS -e ./sysout/obs_yr1_file1.$PBS_JOBID.err
#PBS -o ./sysout/obs_yr1_file1.$PBS_JOBID.out
#PBS -e ./sysout/obs_yr2_file1.$PBS_JOBID.err
#PBS -o ./sysout/obs_yr2_file1.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file1.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file1.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file2.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file2.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file3.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file3.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file4.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file4.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file5.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file5.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file6.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file6.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file7.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file7.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file8.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file8.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file9.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file9.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr1_file10.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr1_file10.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file1.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file1.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file2.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file2.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file3.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file3.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file4.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file4.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file5.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file5.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file6.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file6.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file7.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file7.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file8.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file8.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file9.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file9.$PBS_JOBID.out
#PBS -e ./sysout/sim_yr2_file10.$PBS_JOBID.err
#PBS -o ./sysout/sim_yr2_file10.$PBS_JOBID.out
